vuejs/create-vue

playground/typescript-jsx-router-vuex-with-tests/src/components/HelloWorld.vue
playground/typescript-jsx-router-vuex/src/components/HelloWorld.vue
playground/typescript-jsx-router-with-tests/src/components/HelloWorld.vue
playground/typescript-jsx-router/src/components/HelloWorld.vue
playground/typescript-jsx-vuex-with-tests/src/components/HelloWorld.vue
playground/typescript-jsx-vuex/src/components/HelloWorld.vue
playground/typescript-jsx-with-tests/src/components/HelloWorld.vue
playground/typescript-jsx/src/components/HelloWorld.vue
playground/typescript-router-vuex-with-tests/src/components/HelloWorld.vue
playground/typescript-router-vuex/src/components/HelloWorld.vue
playground/typescript-router-with-tests/src/components/HelloWorld.vue
playground/typescript-router/src/components/HelloWorld.vue
playground/typescript-vuex-with-tests/src/components/HelloWorld.vue
playground/typescript-vuex/src/components/HelloWorld.vue
playground/typescript-with-tests/src/components/HelloWorld.vue
playground/typescript/src/components/HelloWorld.vue
template/code/typescript-default/src/components/HelloWorld.vue
template/code/typescript-router/src/components/HelloWorld.vue

The `HelloWorld` component was using `String` as a type instead of `string`.

fix: use string as prop type in TS

---

template/base/_gitignore

`.gitignore` had `.vscode`, with this config vscode ignores whole `.vscode` directory including `extensions.json`.
Updated to `.vscode/*` so it allows excluding files via `!` prefix.

fix(template): update gitignore to include extensions.json

---

index.js

The eslint script currently ignores the typescript, test, and prettier flags.

fix: eslint with prettier

---

template/base/.vscode/extensions.json
template/config/typescript/env.d.ts
utils/generateReadme.js

After discussions with @johnsoncodehk and @xiaoxiangmoe, we concluded that it makes more sense for most users to start with the TypeScript Vue Plugin instead of the `.vue` shim.
Take Over Mode is more performant and we would like to recommend it, but turning it on in VSCode takes too many steps. So I chose to only mention it in the README, so that more senior developers can know more about it.

feat: drop .vue shim and recommend typescript vue plugin by default

---

template/base/_gitignore

`vitest` (`c8` to be more accurate)  outputs the coverage results in a `coverage` directory by default.

chore: add coverage to gitignore

---

index.js

Fix package.json dosen't generate `name` when npm init vue set valid targetDir

fix: fix packageName when npm init vue set valid targetDir

---

template/tsconfig/vitest/package.json
template/tsconfig/vitest/tsconfig.app.json
template/tsconfig/vitest/tsconfig.json
template/tsconfig/vitest/tsconfig.vitest.json

Credit to @xiaoxiangmoe 
Fixes #55
Fixes the case that a `.spec.ts` file inside `__test__/` imports a
module outside of `__test__/` (a cross-(typescript-)project reference).
Note that VSCode language service looks for `include` patterns in `references`
top-down, so `tsconfig.app.json` must come before `tsconfig.vitest.json`
so that the `src/**` modules can get the most-accurate type hints.
The previous tsconfig only works for `.vue` imports in `.spec.ts`, which
seems to be a Volar bug. We shouldn't rely on that.
This fix is a more accurate configuration.
Vitest TypeScript projects created prior to `create-vue` 3.1.6 can apply the following patch to the projects:
```patch
From a37c33facf0e5db767bee33a71ad9e9fcd3cf373 Mon Sep 17 00:00:00 2001
From: Haoqun Jiang <haoqunjiang@gmail.com>
Date: …
```

fix: vitest tsconfig should include all files under `src`

---

utils/generateReadme.ts

docs: update the links to the vscode marketplace extensions in the readme

---

scripts/build.mjs

Since this package supports Node 14+, the transpiled `prompts` code is not used.
https://github.com/terkelg/prompts/blob/a0c1777ae86d04e46cb42eb3af69ca74ae5d79e2/index.js#L11-L14
This PR removes that from bundle.
|                        | before     | after         |         diff |
|----------------|-----------:|-----------:|----------:|
|gz                    | 53,746B   | 39,690B   | -14,056B (-26.2%) |
|node_modules| 319,900B | 232,067B | -87,833B (-27.5%) |

perf: exclude transpiled prompts code

---

utils/renderEslint.ts

The ESLint config is currently logged out when a new project is generated.

fix: remove console.log

---

template/base/package.json
template/config/playwright/playwright.config.js
template/config/playwright/playwright.config.ts
utils/generateReadme.ts
utils/getCommand.ts

To make it consistent with the Cypress configurations.
Background: https://twitter.com/haoqunjiang/status/1582692547188920322
Alternative: use `npm run dev` in Cypress configuration, as suggested in https://github.com/vuejs/create-vue/pull/39

refactor!: use prod bundle & preview server for playwright testing on CI

---

scripts/test.mjs
template/base/package.json
template/config/cypress-ct/package.json
template/config/cypress/package.json
utils/generateReadme.ts

for headed environment and testing against dev server.
I think this better reflects the real-world use case.
People don't usually need an app window to run the tests against
the production bundle, but faster feedback loops with dev server are
useful.
Inspired by @elevatebart 's comment on twitter: https://twitter.com/elevatebart/status/1582790882088009728

refactor!: run cypress headlessly by default; add test:*:dev commands 

---

index.ts

Fix the typo in the new 3.4.0 E2E testing choices

fix: typo in `needsE2eTesting` `choices` params

---

index.ts

Supersedes #202
Use a `string` option of `minimist` to stringify the potential numeric project name.

fix: project name with only numbers as an argument (#201)

---

index.ts

fix #209 
~~Refer to the package name rules to convert spaces into `-`.~~
If the project name contains spaces, it seems more reasonable to wrap the terminal output in quotes.

fix: wrap in quotes if the project name contains spaces

---

template/config/cypress/cypress/e2e/example.cy.js

The current link redirects to a 404 page.
I've change the link to [The API Docs](https://docs.cypress.io/api/commands/and)

fix: change link to cypress api docs.

---

index.ts
template/config/playwright/.vscode/extensions.json
utils/renderTemplate.ts

feat: if use playwright, add related extension recommendations

---

template/tsconfig/base/tsconfig.node.json

fix `vite.config.ts` error
```
The import.meta attribute is allowed only when the --module option is es2020, es2022, esnext, system, node16, or nodenext
```

fix: add `module: "ESNext"` to tsconfig.node

---

template/config/typescript/package.json

Fixes #267
It's because I moved the `compilerOptions` from `tsconfig.json` to `tsconfig.app.json` in the 2023-05-05 (v3.6.2) release, but forgot to change the `type-check` script.
This isn't comprehensive because it doesn't check all the sub-projects, but at least it's the same scope as previous versions.
Ideally I hope #274 can work reliably. But now I'm not sure. So let's first fix this bug.

fix: specify the sub-project to type-check

---

template/code/default/src/components/HelloWorld.vue
template/code/router/src/components/HelloWorld.vue
template/code/router/src/components/WelcomeItem.vue
template/code/typescript-default/src/components/HelloWorld.vue
template/code/typescript-default/src/components/WelcomeItem.vue
template/code/typescript-router/src/components/HelloWorld.vue
template/code/typescript-router/src/components/WelcomeItem.vue

Fix the incorrect position of `You did it!` heading and `WelcomeItem` introduced in #271

fix: relative position in h1 and WelcomeItem

---

template/code/default/src/components/TheWelcome.vue
template/code/router/src/components/TheWelcome.vue
template/code/typescript-default/src/components/TheWelcome.vue
template/code/typescript-router/src/components/TheWelcome.vue

Add `rel="noopener"` as other `<a>` tags.
```diff
-    <a href="https://on.cypress.io/component" target="_blank">Cypress Component Testing</a>.
+    <a href="https://on.cypress.io/component" target="_blank" rel="noopener"
+      >Cypress Component Testing</a
+    >.
```

chore: add `rel="noopener"` to the link to `Cypress Component Testing`

---

template/config/typescript/package.json

I was configuring builds with different modes and couldn't run ```yarn build --mode preview```  as I would do normally with simple ```vite build``` in my "build" script because of ```ERROR: Invalid Option: --mode```
Had to spend some time figuring this out, guess it may be a helpfull addition that will prevent someone from getting a similar issue

fix(config/typescript): pass build arguments to build-only command

---

pnpm-lock.yaml
template/config/typescript/package.json

Same as ac58cfd9df9f75eea1e7c9f0555d8bb8e5bd7da1 but fixes #306 for TS projects

feat: replace npm-run-all with npm-run-all2

---

scripts/snapshot.mjs

`zx` start powershell as shell instead of Bash. On Windows systems, `rm rf` is not supported, so I think it would be better to replace it with the fs module.

fix: use fs module to remove project

---

index.ts
locales/en-US.json
locales/zh-CN.json
package.json
scripts/build.mjs
utils/getLanguage.ts

Straightforward i18n solution for prompts messages

feat: i18n solution for prompts messages

---

template/base/jsconfig.json

Create-vue doesn't create a `jsconfig.json` file on the first initialization without TS. Added `jsconfig.json` with aliased paths to base template for out of the box VSCode IntelliSense

feat: add jsconfig.json for base template

---

template/base/src/assets/main.css

- Add padding to anchor tag to make more visible.

Add padding to a tag to make more visualised

---

template/code/router/src/views/HomeView.vue

fix: created vue2 project ts error

---

template/tsconfig/base/tsconfig.app.json
template/tsconfig/base/tsconfig.node.json
template/tsconfig/cypress-ct/tsconfig.cypress-ct.json
template/tsconfig/nightwatch-ct/tsconfig.app.json
template/tsconfig/nightwatch/nightwatch/tsconfig.json
template/tsconfig/vitest/tsconfig.vitest.json

To avoid polluting the root directory with tsconfig.*.tsbuildinfo files.
`outDir` in the base config doesn't work because of https://github.com/vuejs/tsconfig/issues/27#issuecomment-1859708129 Besides, we need this explicit config in `tsconfig.node.json` anyways, as it doesn't extend from `@vue/tsconfig`.
Using `.tmp` instead of `.cache` here to better indicate the purpose.

chore: explicitly set tsBuildInfoFile in tsconfig.*.json files

---

.husky/pre-commit
package.json
pnpm-lock.yaml

husky v9 simplified its setup , see `How to migrate` in https://github.com/typicode/husky/releases/tag/v9.0.1

chore: simplify husky setup

---

locales/zh-Hans.json

Update the i18n translation.
I think `构建` means `build`. `scaffolding` should be translated to `初始化`

i18n: Update zh-Hans.json

---

index.ts
template/eslint/package.json
utils/renderEslint.ts

Re #422 
"extends": ["plugin:playwright/recommended"]

feat: eslint plugin playwright

---

index.ts
template/config/prettier/.vscode/extensions.json
template/config/prettier/.vscode/settings.json
utils/renderEslint.ts

If the user pick prettier, then suggest the prettier .vscode extension, and add the settings.
```
{
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true
}
```
```
{
"recommendations": ["esbenp.prettier-vscode"]
}
```
re #302 
1. Create **template/config/prettier/.vscode**:
1.1. extensions.json
1.2. settings.json
2. render('config/prettier') in **index.ts**
3. Remove logic from **renderEslint.ts** for esbenp.prettier-vscode, as it is now moved to a dedicated file (**template/config/prettier/.vscode/extensions.json**)

feat: add vscode config for prettier

---

LICENSE

After executing the `pnpm build`, the content format of the license file has changed.

chore: format license

---

index.ts
utils/getLanguage.ts

When users configure LANG related information by themselves, irregular spelling or capitalization problems may occur. However, I am not sure whether to throw an error directly to terminate the process at this time or just output the error message and continue to perform the following steps. (The current action I take is to print the error message and continue.)
Related commit https://github.com/vuejs/create-vue/commit/bb11f04a5319cecde4bd6e87c3bbb1612d7a88ae

feat: use `Intl.getCanonicalLocales` check locale

---

template/base/.vscode/extensions.json
utils/generateReadme.ts

refactor: delete Vue.vscode-typescript-vue-plugin

---

index.ts

I saw the command to create Vue using bun on Vuejs.org, but the description after creation is still stuck at npm🙏

fix: Command description for Bun

---

index.ts
scripts/snapshot.mjs
template/config/eslint/.vscode/extensions.json
template/config/eslint/.vscode/settings.json
utils/renderEslint.ts
utils/renderTemplate.ts

If the user picks ESLint, then suggest the ESLint .vscode extension, and add the settings.
**settings.json**
```
{
"editor.codeActionsOnSave": {
"source.fixAll": "explicit"
}
}
```
**extensions.json**
```
{
"recommendations": ["dbaeumer.vscode-eslint"]
}
```
#466 
-  **Created template/config/eslint** dedicated to ESLint's static settings, including .vscode/extensions.json and .vscode/settings.json.
- **Removed the existing code for adding the ESLint extension.**
- **Added code to merge Prettier settings into settings.json instead of overwriting them.**
- **Enabled generation of ESLint and Prettier snapshots.**

feat: add vscode config for ESLint

---

locales/zh-Hant.json

Refine translation for Traditional Chinese by using glossaries used in Taiwan.

i18n: Update zh-Hant.json

---

template/config/vitest/vitest.config.js

Fix : https://github.com/vuejs/create-vue/issues/486

fix: exclude from vitest the playwright e2e/** subfolders

---

.github/ISSUE_TEMPLATE/1-feature_request.md
.github/ISSUE_TEMPLATE/2-bug_report.md
.github/ISSUE_TEMPLATE/3-blank.md
.github/ISSUE_TEMPLATE/config.yml

Overall structure is inspired by https://github.com/vuejs/core/issues/new/choose
Based on the number of issues in this repository, I don't think it's mandatory to hide blank issues.
`config.yml` is based on https://github.com/vuejs/core/blob/main/.github/ISSUE_TEMPLATE/config.yml The only difference is that **feature request link** is **removed** from there.
re #474

feat: issue templates

---

.github/workflows/ci.yml
package.json

The `pnpm/action-setup` on ci and the renovate bot will use this field to install the proper pnpm version

chore: use packageManager field to set pnpm version

---

.github/workflows/ci.yml

pnpm v9 won't run on node v16.
As node v16 is EOL, we can safely remove this job from ci.

chore: drop last node v16 ci job

---

.npmrc

After pnpm releases version [9.0.3](https://github.com/pnpm/pnpm/releases/tag/v9.0.3), when the local pnpm version and packageManger version do not match, an error message will appear and the process will exit when running `pnpm i`.

chore: set `package-manager-strict` to false

---

template/config/devtools/vite.config.js.data.mjs

The other plugins (`vue`, `vueJsx` and `nightwatchPlugin`) all follow the same convention to have a lowercase at the start,
so let's do the same for `vueDevTools`

fix: use lowercase for vueDevTools plugin

---

template/tsconfig/cypress/cypress/e2e/tsconfig.json

It looks like this is no longer necessary and allows developers to use a more modern syntax in the spec files.

fix(cypress): remove es5 from tsconfig

---

template/config/playwright/playwright.config.js

When running Playwright end-to-end testing from [Playwright Test for VSCode](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright), an error is thrown:
```
Error: Process from config.webServer was not able to start. Exit code: 1
```
This is probably because the extension runs without adding `node_modules/.bin` to `PATH` like `npm run` does.
This PR uses `npm run` to start the server and adjusts the `port` according to the default port of `vite dev` or `vite preview`.

fix(playwright): use `npm run` to start the server on default port

---

.github/workflows/ci.yml
.prettierignore
__test__/locale.spec.ts
__test__/renderEslint.spec.ts
index.ts
scripts/snapshot.mjs
template/eslint/package.json
utils/renderEslint.ts

The plugin is now officillay recommended, so let's add it to the eslint config when selecting both eslint and vitest.
On top of #558

feat: add @vitest/eslint-plugin when using vitest 

---

README.md
template/base/vite.config.js.ejs
template/code/default/src/components/HelloWorld.vue
template/code/default/src/components/TheWelcome.vue
template/code/router/src/components/HelloWorld.vue
template/code/router/src/components/TheWelcome.vue
template/code/typescript-default/src/components/HelloWorld.vue
template/code/typescript-default/src/components/TheWelcome.vue
template/code/typescript-router/src/components/HelloWorld.vue
template/code/typescript-router/src/components/TheWelcome.vue
utils/generateReadme.ts

chore: replace vite website link

---

__test__/renderEslint.spec.ts
utils/renderEslint.ts

Also fixes tiny discrepancies:
- all files are now declared with single quotes
- dot notation is preferred to access configs when possible

test: re-add eslint unit tests

---

package.json
pnpm-lock.yaml
renovate.json
scripts/build.mjs

Bumps to latest esbuild, allowing to remove the type assertion hack
Also re-enable renovate updates for esbuild

chore: bump esbuild version to v0.24

---

template/base/.vscode/settings.json

We now have *a lot* of configuration files at the project's root. It would help to have them grouped in the editor.
Many people aren't aware of this feature, so I'm adding a default configuration to the base template to raise awareness.
This is a very rudimentary configuration; only patterns relevant to this project are included. Users can customize it further themselves.
Or they can use a more advanced share configuration like https://github.com/antfu/vscode-file-nesting-config
After applying the settings:
The expanded view:

feat: add vscode file nesting config to base template

---

package.json
pnpm-lock.yaml

Remove `kolorist` from package.json as the project now uses `kleur/colors`.

chore: delete kolorist as the project now uses kleur/colors

---

template/config/eslint/.vscode/extensions.json

This PR adds the EditorConfig.EditorConfig extension to the .vscode/extensions.json file when ESLint is selected during the create-vue project setup. This complements the [recent update](https://github.com/vuejs/create-eslint-config/commit/1d657db63bf500c0d8979cd5818d3dc1a9c23498) where .editorconfig is now added by default.

feat: add EditorConfig to .vscode/extensions.json when ESLint is selected.

---

LICENSE
scripts/build.mjs

Excerpt from https://github.com/vitejs/vite/pull/18366

chore: mark template files as CC0

---

index.ts
locales/en-US.json
locales/fr-FR.json
locales/tr-TR.json
locales/zh-Hans.json
locales/zh-Hant.json
package.json
pnpm-lock.yaml
utils/renderEslint.ts

Bumped `@vue/create-eslint-config` to 0.6.0 to support the new feature.
Note:
The `scripts` field generated in package.json for ESLint/Oxlint/Prettier
is now handled by `@vue/create-eslint-config` instead of here.
[Relevant commits](https://github.com/vuejs/create-eslint-config/compare/v0.5.0...v0.6.0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346).
Hope I got the French & Turkish translations right.

feat: add experimental Oxlint integration

---

template/config/typescript/package.json

It was introduced to work around a bug in `vue-tsc` that has been fixed in https://github.com/vuejs/language-tools/pull/3218 so no longer necessary.

perf: remove `--force` from the `type-check` script

---

template/tsconfig/base/tsconfig.app.json
template/tsconfig/nightwatch-ct/tsconfig.app.json

Per the [official documentation](https://www.typescriptlang.org/tsconfig/#baseUrl):
> This feature was designed for use in conjunction with AMD module loaders in the browser, and is not recommended in any other context. As of TypeScript 4.1, baseUrl is no longer required to be set when using paths.

refactor: remove `baseUrl` from all TSConfig files

---

__test__/getCommand.spec.ts
utils/getCommand.ts

If the package manager is bun and the command is build generate 'bun run build' as the command to invoke the build script instead of the built-in 'bun build' command.
Resolves #614

Add run to build command when using bun

---

template/tsconfig/base/tsconfig.app.json
template/tsconfig/base/tsconfig.node.json
template/tsconfig/cypress-ct/tsconfig.cypress-ct.json
template/tsconfig/nightwatch-ct/tsconfig.app.json
template/tsconfig/nightwatch/nightwatch/tsconfig.json
template/tsconfig/vitest/tsconfig.vitest.json

We are only using `references` in a solution-style tsconfig. According to discussions at https://github.com/microsoft/TypeScript/issues/60465, such usage doesn't require `composite: true` to be set in sub-configs.
Removing this field loosens the constraints on these configs that all checked files to be explicitly listed in `files` or `includes`.
After this change, type errors in source code would only be reported twice if they're also imported by unit test specs, in contrast to always be reported twice prior to the change.
I know this is not ideal yet, but it's still an improvement, and might help catch some edge cases such as https://github.com/vuejs/create-vue/issues/437#issuecomment-2468910155
In the long run, we should still keep an eye on https://github.com/vuejs/create-vue/pull/549 …

fix: remove `composite: true` from tsconfigs

---

.github/workflows/ci.yml

Simplify the CI pipeline for a cleaner workflow; and avoid the parallelism limit when we add more flags to the CLI.
Most of the time, the new workflow's total duration would be shorter or similar to the previous one (longer job execution time but less queueing time[^1]), but sometimes, Windows Cypress tests took too long when cache misses.
TODOs:
I'd like to move that into a separate PR because it requires changing the snapshot script, so not a mere CI change.
TO DECIDE:
[^1]: there can be only 20 concurrent jobs on [GitHub Free plan](https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits)

ci: simplify CI matrix and more comprehensive tests

---

.github/workflows/ci.yml
index.ts
scripts/snapshot.mjs
template/bare/base/src/App.vue
template/bare/cypress-ct/src/__tests__/App.cy.js
template/bare/nightwatch-ct/src/__tests__/App.spec.js
template/bare/typescript/src/App.vue
template/bare/vitest/src/__tests__/App.spec.js
utils/trimBoilerplate.ts

Closes #112
Closes #186
Closes #300
Closes #637
~~The minimal template is a cut-down version of the default template;
therefore, the `--minimal` flag is mutually exclusive with all other flags.~~
I chose not to include it in the prompts because it's a very specific
use case, and it's not a good idea to clutter the CLI with too many
options that are not commonly used.
~~I didn't design it as an add-on because the logic would be too complex,
and the use case would be even more niche.~~

feat: use a `--bare` flag to generate a template without too much boilerplate

---

README.md
index.ts

Add documentation for the CLI flags. I think most of them are stable now.
I'm thinking about moving `--prettier` to a separate flag. But even in that case, `--eslint-with-prettier` can still be supported without much effort, so I choose to document it anyway.

feat: add `--help` and `--version` options

---

utils/getLanguage.ts

In different environments, the error message output by this API is inconsistent. refer https://github.com/mdn/interactive-examples/pull/2741#issuecomment-1961443468

fix: extend `Intl.getCanonicalLocales` error message

---

index.ts

Just quick fixing a typo in help message `FEATURE_FLGAS` -> `FEATURE_FLAGS`

fix: update help message

---

utils/getLanguage.ts

Avoid warnings in environments like #648

fix: don't show error when locale is C/C.UTF-8

---

index.ts
template/base/vite.config.js.data.mjs
utils/trimBoilerplate.ts

With v3.13.0, the generated tests were using the `.js` extension. See https://github.com/vuejs/create-vue-templates/tree/v3.13.0/bare-typescript-vitest/src/__tests__ for example
We now render all files _before_ renaming them with the .ts extension if needed.

fix: use ts files when necessary with --bare option

---

README.md

The old command will show the help of `npm create`, not the help of `create-vue`.
Current documentation says we can use `npm create vue@latest -- --help` to show the help of `create-vue`, but I found it will print the help of `npm create`. I'm not sure if it's a bug of `npm`, but `npx create-vue@latest -- --help` works fine.
Windows 11 + npm 10.9.0

fix: correct the command to show help in README.md

---

.github/workflows/ci.yml
__test__/renderEslint.spec.ts
scripts/snapshot.mjs
template/tsconfig/base/tsconfig.node.json
utils/renderEslint.ts

ESLint 9.18 unflagged `eslint.config.ts` support, therefore it's necessary to add `eslint.config.*` to `tsconfig.node.json` to avoid typescript-eslint raising error on that file.

fix: add eslint.config.* to tsconfig.node.json and fix other eslint issues

---

.github/workflows/ci.yml
template/bare/base/src/App.vue
template/bare/cypress-ct/src/__tests__/App.cy.js
template/bare/nightwatch-ct/src/__tests__/App.spec.js
template/bare/typescript/src/App.vue
template/bare/vitest/src/__tests__/App.spec.js
template/config/nightwatch/tests/e2e/example.js
template/config/playwright/e2e/vue.spec.js
template/config/playwright/e2e/vue.spec.ts

This attempts to fix e2e tests when using `--bare` to make them work out of the box

fix: enable e2e tests for --bare

---

.github/workflows/ci.yml
template/config/cypress/package.json

This approach works with both pnpm 10 and other package managers:
- If Cypress's `postinstall` script has been run, it'll do nothing other than print a message.
- If `postinstall` hasn't been run, it'll download the Cypress binary.
As for why using `prepare` instead of `postinstall`, please refer to the discussion thread where `husky` decided to use `prepare`:
- <https://github.com/typicode/husky/issues/884>

fix: add `cypress install` to `prepare` script to fix pnpm 10 compatibility

---

index.ts

When the projectName is set to a string containing only spaces, the value of the package name field must be set correctly.

fix: correctly set the package name value

---

LICENSE
index.ts
locales/en-US.json
locales/fr-FR.json
locales/tr-TR.json
locales/zh-Hans.json
locales/zh-Hant.json
package.json
pnpm-lock.yaml
scripts/build.mjs
utils/getLanguage.ts

As we are adding more features, the number of toggles is getting out of hand. A multiselect could save a few keystrokes for most users.
I also take this opportunity to change the prompts library to `@clack/prompts`.
(For context: `create-astro`, `sv`, `create-preact`, `create-solid`, `create-qwik` all use `@clack/prompts`, `create-vite` recently switched to `@clack/prompts` too, while `create-next-app` uses `prompts`)
The color library is changed to `picocolors`. IMO `kleur` is still the smaller library because of treeshaking. But `@clack/prompts` already comes with `picocolors` as a dependency, so by not adding `kleur`, we save a few bytes.
---
This is a proof-of-concept PR. I haven't put much consideration into the code style yet. Nor have I updated the i18n messages. I will do that if …

feat!: use a giant multiselect instead of individual toggles for features

---

template/config/prettier/package.json

I noticed that after a project creation, there's a `format` outside of the scripts. That should be caused by the prettier configuration script.
This PR solves that small issue.

chore(config): moving prettier script inside the script section

---

template/code/default/src/components/TheWelcome.vue
template/code/router/src/components/TheWelcome.vue
template/code/typescript-default/src/components/TheWelcome.vue
template/code/typescript-router/src/components/TheWelcome.vue

Update documentation for VS Code extension that suggesting Volar instead of Vue - Official.

Update Vue official extension for VS Code

---

.gitignore
LICENSE
index.ts
package.json
pnpm-lock.yaml
rolldown.config.ts
scripts/snapshot.mjs
utils/getLanguage.ts

It hasn't reached a 1.0 stable release yet, but its functionality already meets our use case. I also take this opportunity to move the bundled file to ESM, too, as [Rolldown handles the `require` call in Node.js more intuitively than esbuild](https://github.com/rolldown/rolldown/pull/2920)

build: use rolldown to bundle the output file

---

LICENSE
rolldown.config.ts

1、After executing `pnpm build`, the LICENSE file is partially updated.
2、Unused parameters begin with an underscore.

refactor: update LICENSE

---

index.ts
locales/en-US.json
locales/fr-FR.json
locales/tr-TR.json
locales/zh-Hans.json
locales/zh-Hant.json
utils/getLanguage.ts

feat: add `rolldown-vite` features

---

package.json

Vite 7 requires Node versions 20.19+ or 22.12+. [Vite docs](https://vite.dev/guide/migration.html).
With older versions of Node, starting the dev server will yield an error:
> crypto.hash is not a function
More details: <https://github.com/vitejs/vite/issues/20287>.
I've aligned the `engines.node` value with `create-vite`:
https://github.com/vitejs/vite/blob/3e81af38a80c7617aba6bf3300d8b4267570f9cf/packages/create-vite/package.json#L23
While `create-vue` itself doesn't require these Node versions, I think it makes sense to align `engines.node` with versions that can run the created project.

chore: align Node version with Vite 7

---

template/base/package.json

chore: base template align node version with vite 7

---

.github/workflows/publish.yml
pnpm-workspace.yaml

This is already the case in other CI workflows, and should fix https://github.com/vuejs/create-vue/pull/801/

chore: use pnpm v10 in publish workflow
