playground/jsx-router-pinia-with-tests/src/views/HomeView.vue
playground/jsx-router-pinia/src/views/HomeView.vue
playground/jsx-router-with-tests/src/views/HomeView.vue
playground/jsx-router/src/views/HomeView.vue
playground/router-pinia-with-tests/src/views/HomeView.vue
playground/router-pinia/src/views/HomeView.vue
playground/router-with-tests/src/views/HomeView.vue
playground/router/src/views/HomeView.vue
template/code/router/src/views/HomeView.vue

fix: remove default router ts

---

playground/jsx-router-pinia-with-tests/src/components/HelloWorld.vue
playground/jsx-router-pinia/src/components/HelloWorld.vue
playground/jsx-router-with-tests/src/components/HelloWorld.vue
playground/jsx-router/src/components/HelloWorld.vue
playground/router-pinia-with-tests/src/components/HelloWorld.vue
playground/router-pinia/src/components/HelloWorld.vue
playground/router-with-tests/src/components/HelloWorld.vue
playground/router/src/components/HelloWorld.vue
playground/typescript-jsx-pinia-with-tests/src/components/HelloWorld.vue
playground/typescript-jsx-pinia/src/components/HelloWorld.vue
playground/typescript-jsx-router-pinia-with-tests/src/components/HelloWorld.vue
playground/typescript-jsx-router-pinia/src/components/HelloWorld.vue
playground/typescript-jsx-router-with-tests/src/components/HelloWorld.vue
playground/typescript-jsx-router/src/components/HelloWorld.vue
playground/typescript-jsx-with-tests/src/components/HelloWorld.vue
playground/typescript-jsx/src/components/HelloWorld.vue
playground/typescript-pinia-with-tests/src/components/HelloWorld.vue
playground/typescript-pinia/src/components/HelloWorld.vue
playground/typescript-router-pinia-with-tests/src/components/HelloWorld.vue
playground/typescript-router-pinia/src/components/HelloWorld.vue
playground/typescript-router-with-tests/src/components/HelloWorld.vue
playground/typescript-router/src/components/HelloWorld.vue
playground/typescript-with-tests/src/components/HelloWorld.vue
playground/typescript/src/components/HelloWorld.vue

fix: remove useless css.

---

template/tsconfig/cypress-ct/tsconfig.app.json
template/tsconfig/cypress-ct/tsconfig.cypress-ct.json
template/tsconfig/cypress-ct/tsconfig.json

As pointed out in https://github.com/vuejs/create-vue/pull/56#issuecomment-1040326589

fix(cypress-ct): avoid cypress types polluting normal source files

---

index.js

按照注释使用空值合并运算符（??）替换逻辑或操作符（||），提高代码可读性。

feat: use `??` instead of `||`, drop Node.js 12 support

---

template/base/.vscode/extensions.json

see announcement https://twitter.com/johnsoncodehk/status/1521126248298139648?cxt=HHwWgMCqhe-QkJwqAAAA for more info 🙂

Change extensions to Vue organization

---

template/base/index.html

related https://github.com/vuejs/create-vue/pull/163#discussion_r990598036

chore: remove void element end tag

---

template/base/src/assets/base.css
template/code/default/src/components/WelcomeItem.vue

chore: remove unified position style

---

utils/renderEslint.ts

Add VSCode extension recommendations for ESLint, Prettier
close #301

feat: add VSCode extension recommendations

---

tsconfig.json

fix: omit the extension and import file ts error

---

README.md

docs: fix broken node.js release link

---

locales/tr-TR.json

Hi :wave:,
Small change, translation of english to turkish for `needsDevTools.message` in tr-TR.json file.
Thank you for considering this contribution to create-vue! I look forward to your feedback and suggestions :raised_hands:.

i18n: Update tr-TR.json

---

utils/getLanguage.ts

https://github.com/vuejs/create-vue/pull/450#pullrequestreview-1908734245

chore: remove ts-ignore

---

.github/workflows/ci.yml

https://github.com/nodejs/node/releases/tag/v22.0.0
Node.js version 22 has been released, and it can be added to the system environment where we run the tests.

ci: test on Node.js 22

---

utils/renderTemplate.ts

Write merged setting config when render template

fix: write merged setting config

---

scripts/snapshot.mjs

feat(#522): update snapshot from devtools to devtools-router-pinia

---

.npmrc

In new versions of pnpm, there is no need to manually set `package-manager-strict=false`.

chore: remove `.npmrc`

---

template/config/vitest/.vscode/extensions.json

feat: add corresponding extensions when using vitest

---

package.json
pnpm-lock.yaml

chore: remove npm-run-all2

---

scripts/build.mjs
utils/renderEslint.ts

The comment was appearing in the generated config

fix(eslint): remove comment from generated config

---

template/code/default/src/components/TheWelcome.vue
template/code/router/src/components/TheWelcome.vue
template/code/typescript-default/src/components/TheWelcome.vue
template/code/typescript-router/src/components/TheWelcome.vue

fix: typos

---

.github/workflows/ci.yml

ci: update build output

---

rolldown.config.ts

chore: remove unnecessary console [ci skip]

---

index.ts

refactor: use import attributes instead of assert

---

rolldown.config.ts

ref https://rolldown.rs/guide/plugin-development#plugin-hook-filters

refactor: rolldown plugin use filter property

---

.github/workflows/ci.yml
package.json

chore: drop node 18

---

.github/workflows/ci.yml

https://github.com/nodejs/node/releases/tag/v24.0.0

ci: use node 24

---

index.ts

Hopefully I can press enter to quickly select the default as the target directory.

fix: target directory setting default value

---

index.ts
utils/directoryTraverse.ts

When the target folder has a .git folder, we should not need to output the git init command prompt.

fix: do not always output git init information

---

index.ts
locales/en-US.json
locales/fr-FR.json
locales/tr-TR.json
locales/zh-Hans.json
locales/zh-Hant.json
template/bare/base/src/App.vue
template/bare/typescript/src/App.vue
utils/getLanguage.ts

Follow up of https://github.com/vuejs/create-vue/pull/636
Making the option more visible to regular users.

feat: add a prompt to skip example code

---

rolldown.config.ts

Keep consistent with 3.15.1 and earlier versions, and add version information.

feat: bundle file add banner

---

pnpm-lock.yaml

chore: run dedupe
